FROM golang:1.23-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.1

# Install curl and kubectl
RUN apk update && apk add --no-cache curl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/kubectl

COPY go.mod go.sum ./
RUN go mod download

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
CMD ["air", "-c", ".air.toml"]
