/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/slo` | `/slo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/services/[id]` | `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/logs` | `/logs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/slo` | `/slo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/services/[id]` | `/services/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/ai${`?${string}` | `#${string}` | ''}` | `/ai${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/alerts${`?${string}` | `#${string}` | ''}` | `/alerts${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/incidents${`?${string}` | `#${string}` | ''}` | `/incidents${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/logs${`?${string}` | `#${string}` | ''}` | `/logs${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/slo${`?${string}` | `#${string}` | ''}` | `/slo${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/slo` | `/slo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `${'/(app)'}/services/${Router.SingleRoutePart<T>}` | `/services/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/services/[id]` | `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
